[package]
name = "converge"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
svg = "0.13.1"
rand = "0.8.5"
rayon = "1.7.0"
resvg = "0.42.0"
usvg = "0.28.0"
tiny-skia = "0.8.2"
eframe = "0.28.1"
plotters = "0.3.1"
egui = "0.28.1"
egui_plot = "0.28.1"
